version: '3.8'

services:
  ubuntu-container:
    image: ubuntu:24.04
    container_name: ubuntu_1
    environment:
      - abc=example_value
    volumes:
      - C:\github\htl-stp-et\sj2024-25\5B-FI-Gr1\docker\ubuntu-server\compose\testdata:/test
    tty: true
